/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./../../views/operation/components/Content.vue')['default']
    Header: typeof import('./../../views/operation/components/Header.vue')['default']
    Icon: typeof import('./../../components/icon/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./../../views/operation/components/Sider.vue')['default']
    SvgIcon: typeof import('./../../components/icon/SvgIcon.vue')['default']
  }
}
